name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"     # runs daily at midnight UTC
  workflow_dispatch:        # lets you run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: NyKRiX
          outputs: dist/snake.svg

      - name: Commit generated snake
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "generate snake animation"
          add: "dist/snake.svg"
